[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  [".oh-my-zsh".pull]
    args = ["--ff-only"]

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "git-repo"
  url = "https://github.com/romkatv/powerlevel10k.git"
  [".oh-my-zsh/custom/themes/powerlevel10k".pull]
    args = ["--ff-only"]

[".zinit"]
  type = "git-repo"
  url = "https://github.com/zdharma-continuum/zinit.git"
  [".zinit".pull]
    args = ["--ff-only"]

[".tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux.git"
  [".tmux".pull]
    args = ["--ff-only"]

[".config/nvim"]
  type = "git-repo"
  url = "git@github.com:LazyVim/starter.git"
  [".config/nvim".pull]
    args = ["--ff-only"]

["Library/Application Support/iTerm2/ColorSchemes/iterm2-color-schemes"]
  type = "git-repo"
  url = "https://github.com/mbadolato/iTerm2-Color-Schemes.git"
  ["Library/Application Support/iTerm2/ColorSchemes/iterm2-color-schemes".clone]
    args = ["--depth=1"]
  ["Library/Application Support/iTerm2/ColorSchemes/iterm2-color-schemes".pull]
    args = ["--ff-only"]

["Library/Rime"]
  type = "archive"
  url = "https://github.com/iDvel/rime-ice/archive/refs/heads/main.tar.gz"
  stripComponents = 1
